# Generated by Django 4.0 on 2021-12-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Title')),
                ('thumbnail', models.ImageField(default='', upload_to='static/blog/assets/img/static/thumbnail/%Y/%m/%d', verbose_name='Thumbnail')),
                ('content', models.TextField(default='', max_length=100000, verbose_name='Content')),
                ('published', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
