# Generated by Django 4.0 on 2021-12-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Judul Carousel')),
                ('desc', models.TextField(default='', help_text='masukkan deskripsi yang singkat padat jelas (usahakan tidak terlalu panjang)', max_length=255, verbose_name='Deskripsi Carousel')),
            ],
        ),
    ]
