# Generated by Django 4.0 on 2021-12-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='background',
            field=models.ImageField(default='', upload_to='static/assets/images/carousel/%Y/%m/%d', verbose_name='Foto Background'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='desc',
            field=models.TextField(default='', help_text='masukkan deskripsi yang singkat padat dan jelas (usahakan tidak terlalu panjang)', max_length=255, verbose_name='Deskripsi Carousel'),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(default='', upload_to='static/assets/images/clients/%Y/%m/%d', verbose_name='Logo Client'),
        ),
    ]
