# Generated by Django 4.0 on 2021-12-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_carousel_background_alter_carousel_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(default='', max_length=500, verbose_name='Link Social Media')),
                ('logo', models.CharField(default='', help_text='sumber logo dari https://fontawesome.com/v4.7/icons/ contoh: <i class="fa fa-instagram" aria-hidden="true"></i>', max_length=255, verbose_name='Logo Social Media')),
            ],
        ),
    ]
