# Generated by Django 4.0 on 2021-12-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_social_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='web',
        ),
    ]
