# Generated by Django 4.0 on 2021-12-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_client_web'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Angka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.IntegerField(max_length=1000000000, verbose_name='Jumlah Projek yang Terlaksana')),
                ('employee', models.IntegerField(max_length=1000000000, verbose_name='Jumlah Karyawan')),
                ('client', models.IntegerField(max_length=1000000000, verbose_name='Jumlah Client')),
                ('experience', models.IntegerField(help_text='sudah berapa tahun pengalaman di bidang ini', max_length=1000000000, verbose_name='Tahun Pengalaman')),
            ],
            options={
                'verbose_name': 'Data Untuk Home',
            },
        ),
    ]
