# Generated by Django 4.0 on 2021-12-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_data_angka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_angka',
            name='client',
            field=models.IntegerField(verbose_name='Jumlah Client'),
        ),
        migrations.AlterField(
            model_name='data_angka',
            name='employee',
            field=models.IntegerField(verbose_name='Jumlah Karyawan'),
        ),
        migrations.AlterField(
            model_name='data_angka',
            name='experience',
            field=models.IntegerField(help_text='sudah berapa tahun pengalaman di bidang ini', verbose_name='Tahun Pengalaman'),
        ),
        migrations.AlterField(
            model_name='data_angka',
            name='project',
            field=models.IntegerField(verbose_name='Jumlah Projek yang Terlaksana'),
        ),
    ]
