# Generated by Django 4.0 on 2021-12-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_data_angka_client_alter_data_angka_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_angka',
            name='client',
            field=models.IntegerField(default='0', verbose_name='Jumlah Client'),
        ),
        migrations.AlterField(
            model_name='data_angka',
            name='employee',
            field=models.IntegerField(default='0', verbose_name='Jumlah Karyawan'),
        ),
        migrations.AlterField(
            model_name='data_angka',
            name='experience',
            field=models.IntegerField(default='0', help_text='sudah berapa tahun pengalaman di bidang ini', verbose_name='Tahun Pengalaman'),
        ),
        migrations.AlterField(
            model_name='data_angka',
            name='project',
            field=models.IntegerField(default='0', verbose_name='Jumlah Projek yang Terlaksana'),
        ),
    ]
